version: "3.8"
services:
  db:
    container_name: "postgres"
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: neptune
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres