ktor:
  application:
    modules:
      - app.netlify.carolineandrade.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  audience: "my-audience"
  issuer: "http://localhost"
  realm: "my realm"
  secret: "123"
db:
  url: "jdbc:postgresql://localhost:5432/neptune"
  user: "root"
  password: "postgres"
  pool: 2
